insert into smashcharacter (nomperso,apparition)values('Mario',1);
insert into smashcharacter (nomperso,apparition)values('Link',1);
insert into smashcharacter (nomperso,apparition)values('Kirby',1);
insert into smashcharacter (nomperso,apparition)values('Pikachu',1);
insert into smashcharacter (nomperso,apparition)values('Donkey Kong',1);
insert into smashcharacter (nomperso,apparition)values('Fox',1);
insert into smashcharacter (nomperso,apparition)values('Samus',1);
insert into smashcharacter (nomperso,apparition)values('Yoshi',1);
insert into smashcharacter (nomperso,apparition)values('Rondoudou',1);
insert into smashcharacter (nomperso,apparition)values('Luigi',1);
insert into smashcharacter (nomperso,apparition)values('Captain Falcon',1);
insert into smashcharacter (nomperso,apparition)values('Ness',1);
insert into smashcharacter (nomperso,apparition)values('Mario',2);
insert into smashcharacter (nomperso,apparition)values('Link',2);
insert into smashcharacter (nomperso,apparition)values('Kirby',2);
insert into smashcharacter (nomperso,apparition)values('Pikachu',2);
insert into smashcharacter (nomperso,apparition)values('Donkey Kong',2);
insert into smashcharacter (nomperso,apparition)values('Fox',2);
insert into smashcharacter (nomperso,apparition)values('Samus',2);
insert into smashcharacter (nomperso,apparition)values('Yoshi',2);
insert into smashcharacter (nomperso,apparition)values('Rondoudou',2);
insert into smashcharacter (nomperso,apparition)values('Luigi',2);
insert into smashcharacter (nomperso,apparition)values('Captain Falcon',2);
insert into smashcharacter (nomperso,apparition)values('Ness',2);
insert into smashcharacter (nomperso,apparition)values('Peach',2);
insert into smashcharacter (nomperso,apparition)values('Bowser',2);
insert into smashcharacter (nomperso,apparition)values('Ice Climbers',2);
insert into smashcharacter (nomperso,apparition)values('Sheik',2);
insert into smashcharacter (nomperso,apparition)values('Zelda',2);
insert into smashcharacter (nomperso,apparition)values('Dr. Mario',2);
insert into smashcharacter (nomperso,apparition)values('Pichu',2);
insert into smashcharacter (nomperso,apparition)values('Falco',2);
insert into smashcharacter (nomperso,apparition)values('Marth',2);
insert into smashcharacter (nomperso,apparition)values('Link Enfant',2);
insert into smashcharacter (nomperso,apparition)values('Ganondorf',2);
insert into smashcharacter (nomperso,apparition)values('Mewtwo',2);
insert into smashcharacter (nomperso,apparition)values('Roy',2);
insert into smashcharacter (nomperso,apparition)values('Mr. Game & Watch',2);
insert into smashcharacter (nomperso,apparition)values('Mario',3);
insert into smashcharacter (nomperso,apparition)values('Link',3);
insert into smashcharacter (nomperso,apparition)values('Kirby',3);
insert into smashcharacter (nomperso,apparition)values('Pikachu',3);
insert into smashcharacter (nomperso,apparition)values('Donkey Kong',3);
insert into smashcharacter (nomperso,apparition)values('Fox',3);
insert into smashcharacter (nomperso,apparition)values('Samus',3);
insert into smashcharacter (nomperso,apparition)values('Yoshi',3);
insert into smashcharacter (nomperso,apparition)values('Rondoudou',3);
insert into smashcharacter (nomperso,apparition)values('Luigi',3);
insert into smashcharacter (nomperso,apparition)values('Captain Falcon',3);
insert into smashcharacter (nomperso,apparition)values('Ness',3);
insert into smashcharacter (nomperso,apparition)values('Peach',3);
insert into smashcharacter (nomperso,apparition)values('Bowser',3);
insert into smashcharacter (nomperso,apparition)values('Ice Climbers',3);
insert into smashcharacter (nomperso,apparition)values('Sheik',3);
insert into smashcharacter (nomperso,apparition)values('Zelda',3);
insert into smashcharacter (nomperso,apparition)values('Falco',3);
insert into smashcharacter (nomperso,apparition)values('Marth',3);
insert into smashcharacter (nomperso,apparition)values('Ganondorf',3);
insert into smashcharacter (nomperso,apparition)values('Mr. Game & Watch',3);
insert into smashcharacter (nomperso,apparition)values('Meta Knight',3);
insert into smashcharacter (nomperso,apparition)values('Pit',3);
insert into smashcharacter (nomperso,apparition)values('Samus sans armure',3);
insert into smashcharacter (nomperso,apparition)values('Wario',3);
insert into smashcharacter (nomperso,apparition)values('Snake',3);
insert into smashcharacter (nomperso,apparition)values('Ike',3);
insert into smashcharacter (nomperso,apparition)values('Dresseur de Pokemon',3);
insert into smashcharacter (nomperso,apparition)values('Diddy Kong',3);
insert into smashcharacter (nomperso,apparition)values('Lucas',3);
insert into smashcharacter (nomperso,apparition)values('Sonic',3);
insert into smashcharacter (nomperso,apparition)values('Roi DaDiDou',3);
insert into smashcharacter (nomperso,apparition)values('Olimar',3);
insert into smashcharacter (nomperso,apparition)values('Lucario',3);
insert into smashcharacter (nomperso,apparition)values('R.O.B.',3);
insert into smashcharacter (nomperso,apparition)values('Link Cartoon',3);
insert into smashcharacter (nomperso,apparition)values('Wolf',3);
insert into smashcharacter (nomperso,apparition)values('Mario',4);
insert into smashcharacter (nomperso,apparition)values('Link',4);
insert into smashcharacter (nomperso,apparition)values('Kirby',4);
insert into smashcharacter (nomperso,apparition)values('Pikachu',4);
insert into smashcharacter (nomperso,apparition)values('Donkey Kong',4);
insert into smashcharacter (nomperso,apparition)values('Fox',4);
insert into smashcharacter (nomperso,apparition)values('Samus',4);
insert into smashcharacter (nomperso,apparition)values('Yoshi',4);
insert into smashcharacter (nomperso,apparition)values('Rondoudou',4);
insert into smashcharacter (nomperso,apparition)values('Luigi',4);
insert into smashcharacter (nomperso,apparition)values('Captain Falcon',4);
insert into smashcharacter (nomperso,apparition)values('Ness',4);
insert into smashcharacter (nomperso,apparition)values('Peach',4);
insert into smashcharacter (nomperso,apparition)values('Bowser',4);
insert into smashcharacter (nomperso,apparition)values('Sheik',4);
insert into smashcharacter (nomperso,apparition)values('Zelda',4);
insert into smashcharacter (nomperso,apparition)values('Dr. Mario',4);
insert into smashcharacter (nomperso,apparition)values('Falco',4);
insert into smashcharacter (nomperso,apparition)values('Marth',4);;
insert into smashcharacter (nomperso,apparition)values('Ganondorf',4);
insert into smashcharacter (nomperso,apparition)values('Mewtwo',4);
insert into smashcharacter (nomperso,apparition)values('Roy',4);
insert into smashcharacter (nomperso,apparition)values('Mr. Game & Watch',4);
insert into smashcharacter (nomperso,apparition)values('Meta Knight',4);
insert into smashcharacter (nomperso,apparition)values('Pit',4);
insert into smashcharacter (nomperso,apparition)values('Samus sans armure',4);
insert into smashcharacter (nomperso,apparition)values('Wario',4);
insert into smashcharacter (nomperso,apparition)values('Ike',4);
insert into smashcharacter (nomperso,apparition)values('Dracaufeu',4);
insert into smashcharacter (nomperso,apparition)values('Diddy Kong',4);
insert into smashcharacter (nomperso,apparition)values('Lucas',4);
insert into smashcharacter (nomperso,apparition)values('Sonic',4);
insert into smashcharacter (nomperso,apparition)values('Roi DaDiDou',4);
insert into smashcharacter (nomperso,apparition)values('Olimar',4);
insert into smashcharacter (nomperso,apparition)values('Lucario',4);
insert into smashcharacter (nomperso,apparition)values('R.O.B.',4);
insert into smashcharacter (nomperso,apparition)values('Link Cartoon',4);
insert into smashcharacter (nomperso,apparition)values('Villageois',4);
insert into smashcharacter (nomperso,apparition)values('Mega Man',4);
insert into smashcharacter (nomperso,apparition)values('Entraîneuse Wii Fit',4);
insert into smashcharacter (nomperso,apparition)values('Harmonie & Luma',4);
insert into smashcharacter (nomperso,apparition)values('Little Mac',4);
insert into smashcharacter (nomperso,apparition)values('Amphinobi',4);
insert into smashcharacter (nomperso,apparition)values('Mii Swordfighter',4);
insert into smashcharacter (nomperso,apparition)values('Mii Brawler',4);
insert into smashcharacter (nomperso,apparition)values('Mii Gunfighter',4);
insert into smashcharacter (nomperso,apparition)values('Palutena',4);
insert into smashcharacter (nomperso,apparition)values('Pit Maléfique',4);
insert into smashcharacter (nomperso,apparition)values('PAC-MAN',4);
insert into smashcharacter (nomperso,apparition)values('Lucina',4);
insert into smashcharacter (nomperso,apparition)values('Daraen',4);
insert into smashcharacter (nomperso,apparition)values('Shulk',4);
insert into smashcharacter (nomperso,apparition)values('Bowser Jr.',4);
insert into smashcharacter (nomperso,apparition)values('Duo Duck Hunt',4);
insert into smashcharacter (nomperso,apparition)values('Ryu',4);
insert into smashcharacter (nomperso,apparition)values('Cloud',4);
insert into smashcharacter (nomperso,apparition)values('Corrin',4);
insert into smashcharacter (nomperso,apparition)values('Bayonetta',4);
insert into smashcharacter (nomperso,apparition)values('Mario',5);
insert into smashcharacter (nomperso,apparition)values('Link',5);
insert into smashcharacter (nomperso,apparition)values('Kirby',5);
insert into smashcharacter (nomperso,apparition)values('Pikachu',5);
insert into smashcharacter (nomperso,apparition)values('Donkey Kong',5);
insert into smashcharacter (nomperso,apparition)values('Fox',5);
insert into smashcharacter (nomperso,apparition)values('Samus',5);
insert into smashcharacter (nomperso,apparition)values('Yoshi',5);
insert into smashcharacter (nomperso,apparition)values('Rondoudou',5);
insert into smashcharacter (nomperso,apparition)values('Luigi',5);
insert into smashcharacter (nomperso,apparition)values('Captain Falcon',5);
insert into smashcharacter (nomperso,apparition)values('Ness',5);
insert into smashcharacter (nomperso,apparition)values('Peach',5);
insert into smashcharacter (nomperso,apparition)values('Bowser',5);
insert into smashcharacter (nomperso,apparition)values('Ice Climbers',5);
insert into smashcharacter (nomperso,apparition)values('Sheik',5);
insert into smashcharacter (nomperso,apparition)values('Zelda',5);
insert into smashcharacter (nomperso,apparition)values('Dr. Mario',5);
insert into smashcharacter (nomperso,apparition)values('Pichu',5);
insert into smashcharacter (nomperso,apparition)values('Falco',5);
insert into smashcharacter (nomperso,apparition)values('Marth',5);
insert into smashcharacter (nomperso,apparition)values('Link Enfant',5);
insert into smashcharacter (nomperso,apparition)values('Ganondorf',5);
insert into smashcharacter (nomperso,apparition)values('Mewtwo',5);
insert into smashcharacter (nomperso,apparition)values('Roy',5);
insert into smashcharacter (nomperso,apparition)values('Mr. Game & Watch',5);
insert into smashcharacter (nomperso,apparition)values('Meta Knight',5);
insert into smashcharacter (nomperso,apparition)values('Pit',5);
insert into smashcharacter (nomperso,apparition)values('Samus sans armure',5);
insert into smashcharacter (nomperso,apparition)values('Wario',5);
insert into smashcharacter (nomperso,apparition)values('Snake',5);
insert into smashcharacter (nomperso,apparition)values('Ike',5);
insert into smashcharacter (nomperso,apparition)values('Dresseur de Pokemon',5);
insert into smashcharacter (nomperso,apparition)values('Diddy Kong',5);
insert into smashcharacter (nomperso,apparition)values('Lucas',5);
insert into smashcharacter (nomperso,apparition)values('Sonic',5);
insert into smashcharacter (nomperso,apparition)values('Roi DaDiDou',5);
insert into smashcharacter (nomperso,apparition)values('Olimar',5);
insert into smashcharacter (nomperso,apparition)values('Lucario',5);
insert into smashcharacter (nomperso,apparition)values('R.O.B.',5);
insert into smashcharacter (nomperso,apparition)values('Link Cartoon',5);
insert into smashcharacter (nomperso,apparition)values('Wolf',5);
insert into smashcharacter (nomperso,apparition)values('Villageois',5);
insert into smashcharacter (nomperso,apparition)values('Mega Man',5);
insert into smashcharacter (nomperso,apparition)values('Entraîneuse Wii Fit',5);
insert into smashcharacter (nomperso,apparition)values('Harmonie & Luma',5);
insert into smashcharacter (nomperso,apparition)values('Little Mac',5);
insert into smashcharacter (nomperso,apparition)values('Amphinobi',5);
insert into smashcharacter (nomperso,apparition)values('Mii Swordfighter',5);
insert into smashcharacter (nomperso,apparition)values('Mii Brawler',5);
insert into smashcharacter (nomperso,apparition)values('Mii Gunfighter',5);
insert into smashcharacter (nomperso,apparition)values('Palutena',5);
insert into smashcharacter (nomperso,apparition)values('Pit Maléfique',5);
insert into smashcharacter (nomperso,apparition)values('PAC-MAN',5);
insert into smashcharacter (nomperso,apparition)values('Lucina',5);
insert into smashcharacter (nomperso,apparition)values('Daraen',5);
insert into smashcharacter (nomperso,apparition)values('Shulk',5);
insert into smashcharacter (nomperso,apparition)values('Bowser Jr.',5);
insert into smashcharacter (nomperso,apparition)values('Duo Duck Hunt',5);
insert into smashcharacter (nomperso,apparition)values('Ryu',5);
insert into smashcharacter (nomperso,apparition)values('Cloud',5);
insert into smashcharacter (nomperso,apparition)values('Corrin',5);
insert into smashcharacter (nomperso,apparition)values('Bayonetta',5);
insert into smashcharacter (nomperso,apparition)values('Inkling',5);
insert into smashcharacter (nomperso,apparition)values('Daisy',5);
insert into smashcharacter (nomperso,apparition)values('Ridley',5);
insert into smashcharacter (nomperso,apparition)values('Simon',5);
insert into smashcharacter (nomperso,apparition)values('Richter',5);
insert into smashcharacter (nomperso,apparition)values('Chrom',5);
insert into smashcharacter (nomperso,apparition)values('Samus Sombre',5);
insert into smashcharacter (nomperso,apparition)values('King K. Rool',5);
insert into smashcharacter (nomperso,apparition)values('Marie',5);
insert into smashcharacter (nomperso,apparition)values('Ken',5);
insert into smashcharacter (nomperso,apparition)values('Félinferno',5);
insert into smashcharacter (nomperso,apparition)values('Plante Piranha',5);
insert into smashcharacter (nomperso,apparition)values('Joker',5);
insert into smashcharacter (nomperso,apparition)values('Héros',5);
insert into smashcharacter (nomperso,apparition)values('Banjo & Kazooie',5);
insert into smashcharacter (nomperso,apparition)values('Terry',5);
insert into smashcharacter (nomperso,apparition)values('Byleth',5);
insert into smashcharacter (nomperso,apparition)values('Min Min',5);
insert into smashcharacter (nomperso,apparition)values('Steve',5);
insert into smashcharacter (nomperso,apparition)values('Séphiroth',5);
insert into smashcharacter (nomperso,apparition)values('Pyra / Mythra',5);
insert into smashcharacter (nomperso,apparition)values('Kazuya',5);
insert into smashcharacter (nomperso,apparition)values('Sora',5);


insert into smashGame (nom)values('Super Smash Bros');
insert into smashGame (nom)values('Super Smash Bros Melee');
insert into smashGame (nom)values('Super Smash Bros Brawl');
insert into smashGame (nom)values('Super Smash Bros For 3DS/Wii U');
insert into smashGame (nom)values('Super Smash Bros Ultimate');

insert into maitrise (nomRang)values('S');
insert into maitrise (nomRang)values('A');
insert into maitrise (nomRang)values('B');
insert into maitrise (nomRang)values('C');
insert into maitrise (nomRang)values('D');

insert into smashuser (pseudo,mail,pssworduser,friendcode,adminator,isbanned)values('Loxy','kino@gmail.com','azerty','4998-5216-4989','t','f');
insert into smashuser (pseudo,mail,pssworduser,adminator,isbanned)values('Sakurai','sakurai@gmail.com','kirby','t','f');
insert into smashuser (pseudo,mail,pssworduser,adminator,isbanned)values('disaro','louis@gmail.com','clown','f','t');